### ISSUE TITLE
Refactoring to classes

### ISSUE THREAD

**Issue by Waxyen** [alxhotel/chromecast-api#26]
Hey all,

I was wondering if you would be interested if I rewrite the code a bit, so that everything is in classes. If you are interested, I can make a pull request with my current changes.

If you're interested in the soft rewrite, I would welcome feedback very much.

**Comment by alxhotel** [comment]
Hi @Waxyen :)

Yes, of course!

You're welcome to do any improvements, including refactoring the code ;)

**Comment by Waxyen** [comment]
Haha, I see you've been busy too. You fixed a bug btw, my Philips Hue does not appear in the found chromecast devices anymore with my latest pull!

**Comment by alxhotel** [comment]
Ah nice! Yeah, I'm taking some productive Christmas holidays this year lol

**Comment by Waxyen** [comment]
I think you're succeeding, the code has improved dramatically in your last commits.

**Comment by alxhotel** [comment]
Fixed by @Waxyen in PR #27
