### ISSUE TITLE
Add possibility to connect to existing session

### ISSUE THREAD

**Issue by Richie765** [alxhotel/chromecast-api#33]
Hi! It would be nice if it was possible to control a running session that was started with a different application, for instance Plex. Then it would be possible to pause/resume through this package.

I tried pause/resume but I get the following error:
```
/home/user/develop/tests/api/node_modules/chromecast-api/lib/device.js:221
    this.player.play(callback)
                ^
TypeError: Cannot read property 'play' of undefined
```
Presumably because the video wasn't started using this package.

Thanks!

**Comment by alxhotel** [comment]
Hi @Richie765,

Thank you very much for the feedback :heart: 

You're totally right. This is a must-have feature.

I'll probably work on this next week. But any PR is welcome :blush:

**Comment by alxhotel** [comment]
Released in 0.3.3 4a160604094947fa6494731350724f6f702e6b85

**Comment by usmanniqbal** [comment]
Hi, Any guideline how can I connect existing session?

**Comment by alxhotel** [comment]
Hi @usmanniqbal,

By default, if you call, for example `pause`, it tries to connect to the existing session.

If you call `play` then it will join the session or create a new one, and the play it.

**Comment by usmanniqbal** [comment]
@alxhotel Thanks, I tried with `pause` directly but that didn't worked, so to handle that first we need to call `getStatus` than call `pause`/`setVolume` or any subsequent function.

`        device.getStatus(function (err, session) {
          if (!err) {
                device.pause(handleError);
          }
          });`

**Comment by Richie765** [comment]
I cannot get this to work, also not after `getStatus`. In both cases I get: `Error: no session started`. Any idea what could be wrong?
