### ISSUE TITLE
Pull Request: avoid catastrophic failure for device.getStatus()

### ISSUE THREAD

**Issue by jhfoo** [alxhotel/chromecast-api#43]
If Chromecast isn't playing a supported app (eg in its do-nothing mode) the first getStatus() returns the expected error. A repeat call throws 'Cannot read property 'getStatus' of undefined' because device.client is not null.

Proposed code change:
```
  // device.js
  getStatus (callback) {
    this._tryJoin((err) => {
      if (err) {
        this.client = null // add this line
        return callback(err)
      }

      this.player.getStatus(callback)
    })
  }
```

**Comment by alxhotel** [comment]
Fixed by @jhfoo in 9264804581de31f25ad4f5607a163e6ac8117eec
