### ISSUE TITLE
Casting local mp3 files to device

### ISSUE THREAD

**Issue by tehuster** [alxhotel/chromecast-api#54]
Is it possible to cast local mp3 files to a device? If not i would like to request this feature.  
Nice work so far!

**Comment by alxhotel** [comment]
Hey @tehuster,

Yep, it's possible.

You just need to setup a local server and use `device.play(mediaURL)` where `mediaURL` is the URL pointing to the mp3 file.

Let me know if you encounter any problems.

**Comment by franciscojfs** [comment]
Hello! I'm having an issue with that.

```
Error: Load failed
    at ...\node_modules\castv2-client\lib\controllers\media.js:75:23
    at fn.onmessage (...\node_modules\castv2-client\lib\controllers\request-response.js:27:7)
````
