### ISSUE TITLE
Local subtitles not working

### ISSUE THREAD

**Issue by korphos** [alxhotel/chromecast-api#55]
Hello, I'm trying to cast with my own generated subtitles.

Here is an example of my media object where 192.168.0.2 is the local IP of my PC with an NodeJS express http server, the local video plays correctly but subtitles don't appear:
```
const media = {
                url : 'http://192.168.0.2/video.mkv',
                subtitles: [{
                   language: 'en-US',
                   name: 'English',
                   url: `http://192.168.0.2/subtitles.vtt`,
                }],
                subtitles_style: {
                    backgroundColor: '#FFFFFF00', // see http://dev.w3.org/csswg/css-color/#hex-notation
                    foregroundColor: '#FFFFFFFF', // see http://dev.w3.org/csswg/css-color/#hex-notation
                    edgeType: 'OUTLINE', // can be: "NONE", "OUTLINE", "DROP_SHADOW", "RAISED", "DEPRESSED"
                    edgeColor: '#000000FF', // see http://dev.w3.org/csswg/css-color/#hex-notation
                    fontScale: 1.2, // transforms into "font-size: " + (fontScale*100) +"%"
                    fontStyle: 'BOLD', // can be: "NORMAL", "BOLD", "BOLD_ITALIC", "ITALIC",
                    fontFamily: 'Droid Sans',
                    fontGenericFamily: 'SANS_SERIF', // can be: "SANS_SERIF", "MONOSPACED_SANS_SERIF", "SERIF", "MONOSPACED_SERIF", "CASUAL", "CURSIVE", "SMALL_CAPITALS"
                }
            }`
```

If I just replace 'http://192.168.0.2/subtitles.vtt' by your example 'https://raw.githubusercontent.com/alxhotel/chromecast-api/master/test/captions_styled.vtt' it works. Even if my subtitles.vtt contains exactly the same text as captions_styled.vtt

The fact that the video is playing proves that my chromecast is able to reach my local express server.

Is that a limitation of Chromecast? Subtitles must be hosted on a HTTPS website maybe?

**Comment by alxhotel** [comment]
Hey @korphos,

Nice catch :+1: 

I was able to reproduce this problem in my machine. It seems like you need to allow CORS. Check out [the docs](https://developers.google.com/cast/docs/media)

> Your subtitle resources must implement CORS.

Once I enabled CORS with this header `Access-Control-Allow-Origin: *`, everything worked fine.

I'll be adding this issue to the docs.

PS: I'm closing this issue, but feel free to reopen it if this solution doesn't fix it.

**Comment by korphos** [comment]
Ok thank you it worked with `Access-Control-Allow-Origin: *`. Strange since it's not needed for the video itself.
