### ISSUE TITLE
Playing local files

### ISSUE THREAD

**Issue by lennertderyck** [alxhotel/chromecast-api#57]
I tried it because i thought it would work, but is it possible to play local video files? I couldn't get it to work. If so, how?
Thanks in advance!

**Comment by alxhotel** [comment]
Hi @lennertderyck,

Right now, you need to setup a local server to stream the content.

Setting up this server inside the library might make it too big. If enough people want this feature I think we can add it. But for know, the simplest way is to set it up yourself.

Let me know if you encounter any problems.
