### ISSUE TITLE
Chromecast iOS app crashes while streaming

### ISSUE THREAD

**Issue by z-ax** [alxhotel/chromecast-api#8]
Hey. Just checked simple example from README and have weird issue: official Chromecast iOS app crashes all time while streaming from node with this.

Kinda weird, had no issues like that with `castv2-client`.

**Comment by alxhotel** [comment]
It's working for me with official Chromecast Android app. I don't have a iOS device so I can't test this.

Can you show your steps on how to reproduce this crash with some logs of node?

**Comment by z-ax** [comment]
Well, the official app crashes directly when streaming starts (or on launch if already started), but node works and streaming doesn't hang. Kinda weird behaviour.

**Comment by alxhotel** [comment]
Let's leave this issue open, just in case there's someone who can help us in this matter

**Comment by z-ax** [comment]
I'll try to get back to this as well in some time. And check the Android app as well then.

**Comment by andeersg** [comment]
I have tested the example from the README and my iOS Chromecast app works as expected. I can play/pause and adjust volume without any crashes.

iOS 10 btw.

**Comment by alxhotel** [comment]
Thanks for testing it @andeersg

I also tried all tests and README examples with Google Home v.1.19.1603 on an iPad Mini 2 with iOS 10.1.1 and it works.

This is probably a bug in an old version of the chromecast app.

If there isn't anything more, I think we can close this issue. @z-ax

**Comment by z-ax** [comment]
In this case surely let's close it, thanks!
I'm currently having lack of time to work on that, but plan to update my app probably next month - will try this lib once again (and report if something goes wrong).
